# Generated by Django 2.1.1 on 2019-08-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('academic_year', models.IntegerField()),
                ('term', models.CharField(choices=[('f', 'Full-Term'), ('m', 'Mid-Term')], max_length=1)),
                ('attendance', models.CharField(choices=[('p', 'Present'), ('a', 'Absent'), ('s', 'Sick'), ('l', 'Leave')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('national_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher'),
        ),
    ]
