# Generated by Django 2.1.1 on 2019-08-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('academic_year', models.IntegerField()),
                ('term', models.CharField(choices=[('f', 'Full-Term'), ('m', 'Mid-Term')], max_length=1)),
                ('first_half_attendance', models.CharField(choices=[('p', 'Present'), ('a', 'Absent'), ('s', 'Sick'), ('l', 'Leave')], max_length=1)),
                ('second_half_attendance', models.CharField(choices=[('p', 'Present'), ('a', 'Absent'), ('s', 'Sick'), ('l', 'Leave')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('academic_year', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('score', models.FloatField()),
                ('term', models.CharField(max_length=1)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('national_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AddField(
            model_name='performance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classapp.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(to='classapp.Subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('student', 'academic_year', 'subject', 'term')},
        ),
    ]
